kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
  namespace: e-stack
  labels:
    app: redis
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
